### ISSUE TITLE
AUC calculation

### ISSUE THREAD

**Issue by Sibojang9** [ronkeizer/PKPDsim#26]
Hi Ron,

Is there any built-in functionality within PKPDsim to calculate the AUC?  If not, we can use still use a third party package to get the AUC of PKPDsim simulation. I am just curious.

Thank you,

Sibo

**Comment by ronkeizer** [comment]
hi Sibo,
no, it is not built-in. I've thought about putting this functionality in, but don't think I will because it is pretty straightforward to implement an AUC compartment yourself and I don't want to extend this package with needless features and arguments. To calculate an AUC, just add a compartment to your system that integrates the concentration over time. E.g. when you have a 1-cmt model:

    pk1 <- new_ode_model(code = "
      dAdt[1] = -KA * A[1]
      dAdt[2] = +KA * A[1] -(CL/V) * A[2]
    ")

just add a third compartment for AUC:

    pk1auc <- new_ode_model(code = "
      dAdt[1] = -KA * A[1]
      dAdt[2] = +KA * A[1] -(CL/V) * A[2]
      dAdt[3] = A[2]/V
    ")
and the AUC will be calculated in compartment 3.

**Comment by Sibojang9** [comment]
That works perfectly.  I am amazingly surprised by that the calculation of AUC could be so simple. No need to do any integration.
